# SPDX-FileCopyrightText: 2025-2026 CocoIndex.io (upstream)
# SPDX-FileCopyrightText: 2026 Knitli Inc. (ReCoco)
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
# SPDX-FileContributor: CocoIndex Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: cocoindex-postgres
services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_PASSWORD: cocoindex
      POSTGRES_USER: cocoindex
      POSTGRES_DB: cocoindex
    ports:
      - 5432:5432
